### ISSUE TITLE
scalars() in SelectPagination

### ISSUE THREAD

**Issue by AdamVerner** [pallets-eco/flask-sqlalchemy#1209] opened 2023-05-25 13:21 UTC
https://github.com/pallets-eco/flask-sqlalchemy/blob/d137db10e733daf1fd2ad24dd59aedc3072d48e5/src/flask_sqlalchemy/pagination.py#L335

Hi, is there any specific reason why the `.scalars()` call is in the pagination? I'm trying to query two objects  at the same time and cannot do so, because the pagination will only return the first one. 
Is that call there necessary? If no, could it be removed?

**Comment by AdamVerner** [comment] 2023-05-25 13:24
Same goes for the `unique`

**Comment by davidism** [comment] 2023-05-25 17:59
Duplicate of #1168

**Closed by davidism** 2023-05-25 17:59 UTC
