### ISSUE TITLE
The latest `flask-sqlalchemy` 2.x release now installs SQLAlchemy 2.x

### ISSUE THREAD

**Issue by guidoiaquinti** [pallets-eco/flask-sqlalchemy#1161] opened 2023-01-31 16:55 UTC
👋  Hi! First, thank you for this great repo! 

I am using `flask-sqlalchemy` in a project and I’m pinning the latest 2.x version (`2.5.1`) as a dependency. Since the SQLAlchemy 2.0 release, installing that version is bringing the latest SQLA release as [we don’t pin/restrict the version](https://github.com/pallets-eco/flask-sqlalchemy/blob/da0e0df80cc368d95dc5a118ce857cead172aded/setup.py#L31) in the package requirements. In my case, it was a breaking change.

From a user perspective, I think we could consider pinning the SQLA version in the 2.x branch.  

Thank you! 🙇

**Comment by davidism** [comment] 2023-01-31 16:58
Duplicate of https://github.com/pallets-eco/flask-sqlalchemy/issues/1158

You are using an unsupported version of Flask-SQLAlchemy, please update to the latest version if possible. Please read https://hynek.me/articles/semver-will-not-save-you/ or watch https://www.youtube.com/watch?v=WSVFw-3ssXM&t. When writing an application, you must use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies, in order get reproducible deployments and to control when you get updates.

**Closed by davidism** 2023-01-31 16:58 UTC
